// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCy5uq2uf_7uWdD6VEQ7ovdMHVtX4WDr8',
    appId: '1:590233827609:web:e09519f1e968fdea6a6d88',
    messagingSenderId: '590233827609',
    projectId: 'signc-cda15',
    authDomain: 'signc-cda15.firebaseapp.com',
    storageBucket: 'signc-cda15.appspot.com',
    measurementId: 'G-EWJYZD0LR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgyFDD-MvCnPu_ncrzAow7rPRCncTMPIU',
    appId: '1:590233827609:android:6cda8e65c2629d166a6d88',
    messagingSenderId: '590233827609',
    projectId: 'signc-cda15',
    storageBucket: 'signc-cda15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJtMHJl0UOOUa8oPn-OhrO2IjA7HtSaMs',
    appId: '1:590233827609:ios:35ac83337ba453bb6a6d88',
    messagingSenderId: '590233827609',
    projectId: 'signc-cda15',
    storageBucket: 'signc-cda15.appspot.com',
    iosBundleId: 'com.example.signc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJtMHJl0UOOUa8oPn-OhrO2IjA7HtSaMs',
    appId: '1:590233827609:ios:35ac83337ba453bb6a6d88',
    messagingSenderId: '590233827609',
    projectId: 'signc-cda15',
    storageBucket: 'signc-cda15.appspot.com',
    iosBundleId: 'com.example.signc',
  );
}
